[package]
name = "nn"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"

[profile.release]
debug = false
debug-assertions = false
opt-level = 3
